/*=============================================================================
 * The MIT License (MIT)
 *
 * Copyright (c) 2025 Che-Hung Lin
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *===========================================================================*/
package ch.lin.downloader.backend.api.domain;

import static ch.lin.downloader.backend.api.domain.DownloaderConfig.TABLE_NAME;
import ch.lin.platform.domain.model.AuditableEntity;
import ch.lin.platform.domain.model.BaseEntity;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

/**
 * Represents the downloader configuration entity stored in the database.
 * <p>
 * This class defines the settings for the downloader, including general
 * behavior and a one-to-one relationship with yt-dlp specific settings. A
 * no-args constructor is generated by Lombok for JPA.
 */
@Entity
@Table(name = TABLE_NAME, indexes = {
    @Index(name = DownloaderConfig.ID_INDEX, columnList = BaseEntity.ID_COLUMN),
    @Index(name = DownloaderConfig.NAME_INDEX, columnList = DownloaderConfig.NAME_COLUMN)}, uniqueConstraints = {
    @UniqueConstraint(columnNames = DownloaderConfig.NAME_COLUMN)})
@Getter
@EqualsAndHashCode(of = {"name", "enabled", "duration", "startDownloadAutomatically", "removeCompletedJobAutomatically",
    "clientId", "clientSecret", "threadPoolSize", "maxQueueSize", "ytDlpConfig"}, callSuper = false)
@SuperBuilder(toBuilder = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class DownloaderConfig extends AuditableEntity {

    /**
     * The name of the downloader configuration table in the database.
     */
    public static final String TABLE_NAME = "downloader_config";

    /**
     * The name of the index for the ID column.
     */
    public static final String ID_INDEX = "downloader_config_id_index";

    /**
     * The name of the name column in the database.
     */
    public static final String NAME_COLUMN = "name";

    /**
     * The name of the index for the name column.
     */
    public static final String NAME_INDEX = "downloader_config_name_index";

    /**
     * The name of the enabled column in the database.
     */
    public static final String ENABLED_COLUMN = "enabled";

    /**
     * The name of the duration column in the database.
     */
    public static final String DURATION_COLUMN = "duration";

    /**
     * The name of the start download automatically column in the database.
     */
    public static final String START_DOWNLOAD_AUTOMATICALLY_COLUMN = "start_download_automatically";

    /**
     * The name of the remove completed job automatically column in the
     * database.
     */
    public static final String REMOVE_COMPLETED_JOB_AUTOMATICALLY_COLUMN = "remove_completed_job_automatically";

    /**
     * The name of the client id column in the database.
     */
    public static final String CLIENT_ID_COLUMN = "client_id";

    /**
     * The name of the client secret column in the database.
     */
    public static final String CLIENT_SECRET_COLUMN = "client_secret";

    /**
     * The name of the thread pool size column in the database.
     */
    public static final String THREAD_POOL_SIZE_COLUMN = "thread_pool_size";

    /**
     * The name of the maximum queue size column in the database.
     */
    public static final String MAX_QUEUE_SIZE_COLUMN = "max_queue_size";

    /**
     * The name of the yt-dlp config ID column in the database.
     */
    public static final String YTDLP_CONFIG_ID_COLUMN = "ytdlp_config_id";

    /**
     * The name of the foreign key constraint for the yt-dlp config
     * relationship.
     */
    public static final String FK_DOWNLOADER_CONFIG_YTDLP = "fk_downloader_config_ytdlp";

    /**
     * The unique name of the configuration.
     */
    @NotNull
    @Column(name = DownloaderConfig.NAME_COLUMN, nullable = false)
    private String name;

    /**
     * Indicates whether the configuration is enabled.
     */
    @NotNull
    @Column(name = DownloaderConfig.ENABLED_COLUMN, nullable = false)
    @Setter
    private Boolean enabled;

    /**
     * The duration in seconds for a download job before it times out.
     */
    @NotNull
    @Column(name = DownloaderConfig.DURATION_COLUMN, nullable = false)
    @Setter
    private Integer duration;

    /**
     * Indicates whether to start downloads automatically upon job creation.
     */
    @Column(name = DownloaderConfig.START_DOWNLOAD_AUTOMATICALLY_COLUMN)
    @Setter
    private Boolean startDownloadAutomatically;

    /**
     * Indicates whether to remove completed jobs from the list automatically.
     */
    @Column(name = DownloaderConfig.REMOVE_COMPLETED_JOB_AUTOMATICALLY_COLUMN)
    @Setter
    private Boolean removeCompletedJobAutomatically;

    /**
     * The client ID for accessing the YouTube Hub's REST API.
     */
    @Column(name = DownloaderConfig.CLIENT_ID_COLUMN)
    @Setter
    private String clientId;

    /**
     * The client secret for accessing the YouTube Hub's REST API.
     */
    @Column(name = DownloaderConfig.CLIENT_SECRET_COLUMN)
    @Setter
    private String clientSecret;

    /**
     * The size of the thread pool for concurrent downloads.
     */
    @NotNull
    @Column(name = DownloaderConfig.THREAD_POOL_SIZE_COLUMN, nullable = false)
    @Setter
    private Integer threadPoolSize;

    /**
     * The maximum size of the executor queue before skipping new task fetches.
     */
    @Column(name = DownloaderConfig.MAX_QUEUE_SIZE_COLUMN)
    @Setter
    private Integer maxQueueSize;

    /**
     * The associated yt-dlp configuration. This is a one-to-one relationship,
     * meaning each {@code DownloaderConfig} has exactly one
     * {@link YtDlpConfig}. Cascade operations ensure that the lifecycle of
     * {@code YtDlpConfig} is bound to this entity.
     */
    @OneToOne(cascade = CascadeType.ALL, optional = false, orphanRemoval = true)
    @JoinColumn(name = DownloaderConfig.YTDLP_CONFIG_ID_COLUMN, foreignKey = @ForeignKey(name = DownloaderConfig.FK_DOWNLOADER_CONFIG_YTDLP))
    @Setter
    private YtDlpConfig ytDlpConfig;

    /**
     * Creates a new DownloaderConfig with the specified name.
     *
     * @param name The unique name for this configuration.
     */
    public DownloaderConfig(String name) {
        this();
        this.name = name;
    }
}
